# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -r vehicle.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p_Vehicle', contains = 'C++Reference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of Vehicle_Axles

`Vehicle_Axles` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_Vehicle_Axles', self, as.logical(.copy), PACKAGE='vehicle');
  
}

attr(`Vehicle_Axles`, 'returnType') = 'integer'
attr(`Vehicle_Axles`, "inputTypes") = c('_p_Vehicle')
class(`Vehicle_Axles`) = c("SWIGFunction", class('Vehicle_Axles'))

# Start of Vehicle_Available_set

`Vehicle_Available_set` = function(self, s_Available)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  s_Available = as.logical(s_Available);
  ;.Call('R_swig_Vehicle_Available_set', self, s_Available, PACKAGE='vehicle');
  
}

attr(`Vehicle_Available_set`, 'returnType') = 'void'
attr(`Vehicle_Available_set`, "inputTypes") = c('_p_Vehicle', 'logical')
class(`Vehicle_Available_set`) = c("SWIGFunction", class('Vehicle_Available_set'))

# Start of Vehicle_Available_get

`Vehicle_Available_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_Vehicle_Available_get', self, as.logical(.copy), PACKAGE='vehicle');
  
}

attr(`Vehicle_Available_get`, 'returnType') = 'logical'
attr(`Vehicle_Available_get`, "inputTypes") = c('_p_Vehicle')
class(`Vehicle_Available_get`) = c("SWIGFunction", class('Vehicle_Available_get'))

# Start of new_Vehicle

`Vehicle__SWIG_0` = function()
{
  ;ans = .Call('R_swig_new_Vehicle__SWIG_0', PACKAGE='vehicle');
  ans <- if (is.null(ans)) ans
  else new("_p_Vehicle", ref=ans);
  
  reg.finalizer(ans@ref, delete_Vehicle);
  ans
  
}

attr(`Vehicle__SWIG_0`, 'returnType') = '_p_Vehicle'
class(`Vehicle__SWIG_0`) = c("SWIGFunction", class('Vehicle__SWIG_0'))

# Start of new_Vehicle

`Vehicle__SWIG_1` = function(ax)
{
  ax = as.integer(ax);
  
  if(length(ax) > 1) {
    warning("using only the first element of ax");
  };
  
  ;ans = .Call('R_swig_new_Vehicle__SWIG_1', ax, PACKAGE='vehicle');
  ans <- if (is.null(ans)) ans
  else new("_p_Vehicle", ref=ans);
  
  reg.finalizer(ans@ref, delete_Vehicle);
  ans
  
}

attr(`Vehicle__SWIG_1`, 'returnType') = '_p_Vehicle'
attr(`Vehicle__SWIG_1`, "inputTypes") = c('integer')
class(`Vehicle__SWIG_1`) = c("SWIGFunction", class('Vehicle__SWIG_1'))

`Vehicle` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 2
  if (argc == 0) {
    f <- Vehicle__SWIG_0; 
  } else if (argc == 1) {
    if ( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) {
      f <- Vehicle__SWIG_1; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for Vehicle with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of delete_Vehicle

`delete_Vehicle` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_delete_Vehicle', self, PACKAGE='vehicle');
  
}

attr(`delete_Vehicle`, 'returnType') = 'void'
attr(`delete_Vehicle`, "inputTypes") = c('_p_Vehicle')
class(`delete_Vehicle`) = c("SWIGFunction", class('delete_Vehicle'))

# Start of accessor method for Vehicle
setMethod('$', '_p_Vehicle', function(x, name)

{
  accessorFuns = list('Axles' = Vehicle_Axles, 'Available' = Vehicle_Available_get);
  vaccessors = c('Available');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for Vehicle
# Start of accessor method for Vehicle
setMethod('$<-', '_p_Vehicle', function(x, name, value)

{
  accessorFuns = list('Available' = Vehicle_Available_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_Vehicle', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('Available' = Vehicle_Available_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for Vehicle
setMethod('delete', '_p_Vehicle', function(obj) {delete_Vehicle(obj)})


